[package]
name = "scss_lib"
version = "0.13.4"
description = "A Sass compiler written purely in Rust"
readme = "../../README.md"
license = "MIT"
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css", "web"]
edition = "2021"
include = [
    "src",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "Cargo.lock",
    "LICENSE",
]
default-run = "scss_lib"
rust-version = "1.70"

[[bin]]
name = "scss_lib"
path = "src/main.rs"
required-features = ["commandline"]

[lib]
name = "scss_lib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
bench = false


[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --features=macro --no-deps --open
features = ["macro"]
rustdoc-args = ["--cfg", "doc_cfg"]

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }
getrandom = { version = "0.2", features = ["js"] }
scss_rust = { path = "../scss_rust", version = "=0.13.4", default-features = false }
clap = { version = "4.3.10", optional = true }

[features]
# todo: no commandline by default
default = ["commandline", "random"]
# Option (enabled by default): build a binary using clap
commandline = ["clap"]
random = ["scss_rust/random"]
wasm-exports = ["scss_rust/wasm-exports", "wasm-bindgen"]

[dev-dependencies]
tempfile = "3.3.0"
paste = "1.0.3"
